### ISSUE TITLE
Recommend 'use strict' in Licenses Config Files

### ISSUE THREAD

**Issue by Kurt-von-Laven** [tophat/yarn-plugin-licenses#12]
**Is your feature request related to a problem? Please describe.**

Strict mode helps catch some mistakes, so recommending its use will slightly aid future downstream developers.

**Describe the solution you'd like**

Add `'use strict'` to the top of sample license config files.

**Describe alternatives you've considered**

Doing nothing is a perfectly reasonable alternative here.

**Additional context**

This is simply something that occurred to me while dealing with other .js config files based on the samples from their projects.

**Comment by Kurt-von-Laven** [comment]
Apologies for closing the original PR by accident, @noahnu. I foolishly opened it from my master branch and subsequently forgot it was still open when I went to make an unrelated change.

**Comment by noahnu** [comment]
We're using Typescript, I don't believe strict mode has any effect.

**Comment by Kurt-von-Laven** [comment]
See #18 where I have reopened the PR. This is only about JS files and mainly the downstream config files. It's not for my benefit since my config file already works and uses strict mode, but it can catch things like use of undeclared variables.

**Comment by noahnu** [comment]
For the files within the project we have linters setup that catch issues like that in CI. You can try commit an unused variable, it'll throw an error. For the config examples, that still seems like a detail left to the developer. It's outside the purview of this plugin in my opinion.

**Comment by Kurt-von-Laven** [comment]
Ah, I didn't realize that; makes sense.
