### ISSUE TITLE
Plugin not usable with latest yarn

### ISSUE THREAD

**Issue by olee** [tophat/yarn-plugin-licenses#14]
It seems the following line is not the correct way to specify the command path anymore as the command is unusable for me:
https://github.com/tophat/yarn-plugin-licenses/blob/c2abd459501318dded85841a748bc513b49b3b11/src/index.ts#L51

Also in the yarn docs it says to use `.addPath` instead:
https://yarnpkg.com/advanced/plugin-tutorial#adding-commands

**Comment by thesabbir** [comment]
I'm facing the same issue @olee 

```
Usage Error: Couldn't find a script named "licenses".
```

**Comment by Kurt-von-Laven** [comment]
I have been using this tool for a while, and it never worked for me at yarn v2, but it does at yarn v3 (e.g., `yarn set version 3.0.0-rc.6`).

**Comment by noahnu** [comment]
Fixed & tested for Yarn v3.0.0 which is stable now.
