### ISSUE TITLE
Support Deprecated License Object Format

### ISSUE THREAD

**Issue by Kurt-von-Laven** [tophat/yarn-plugin-licenses#15]
**Is your feature request related to a problem? Please describe.**

Some old packages like [deep-is@0.1.3](https://github.com/thlorenz/deep-is/blob/v0.1.3/package.json) use [the deprecated `license` object format](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license) rather than a string.

**Describe the solution you'd like**

It would be ideal if the old format were supported since it's unambiguous, and small packages that predate the switch to SPDX are fairly likely to be unmaintained by now.

**Describe alternatives you've considered**

As a workaround, one can manually validate license compatibility for these packages and then configure CI to ignore specific test failures. A more convenient workaround might be to offer the package name and version number as parameters to `isValidLicense` so that the configuration can contain an allow list of manually validated licenses.

A more ambitious alternative is for all users of this plugin to open pull requests against all packages that still use the `licenses` property in their package.json and subsequently nudge all downstream packages to upgrade to the newer version of this package. That is a great civic action to take regardless, but this significantly increases the amount of friction involved in the typically thankless task of license auditing that is rarely prioritized to begin with.

**Additional context**

deep-is@0.1.3 is an indirect dependency of [jest@27.0.5](https://github.com/facebook/jest/tree/v27.0.5), and I have filed thlorenz/deep-is#9.

**Comment by Kurt-von-Laven** [comment]
deep-is [now uses the new `license` string format](thlorenz/deep-is#9) in [v0.1.4](https://github.com/thlorenz/deep-is/blob/v0.1.4/package.json). If someone finds another prominent example of the deprecated format, I would be curious to hear about it.

**Comment by drazisil** [comment]
Ah, sorry for the dupe issue. :+1:
